# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_url.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(982, 542)
        self.url = QtWidgets.QPushButton(Form)
        self.url.setGeometry(QtCore.QRect(20, 90, 101, 23))
        self.url.setObjectName("url")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(140, 90, 821, 441))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.texturl = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.texturl.setObjectName("texturl")
        self.verticalLayout_3.addWidget(self.texturl)
        self.textsumber = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.textsumber.setFont(font)
        self.textsumber.setObjectName("textsumber")
        self.verticalLayout_3.addWidget(self.textsumber)
        self.textringkasan = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.textringkasan.setFont(font)
        self.textringkasan.setObjectName("textringkasan")
        self.verticalLayout_3.addWidget(self.textringkasan)
        self.ringkasan = QtWidgets.QPushButton(Form)
        self.ringkasan.setGeometry(QtCore.QRect(18, 320, 101, 23))
        self.ringkasan.setObjectName("ringkasan")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(0, 50, 991, 16))
        self.frame_3.setAutoFillBackground(False)
        self.frame_3.setStyleSheet("background-color: rgb(26, 81, 84);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 991, 61))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color:#04b1c7;\n"
"color: rgb(232, 231, 232);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(350, 10, 311, 39))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.save = QtWidgets.QPushButton(Form)
        self.save.setGeometry(QtCore.QRect(100, 500, 31, 31))
        self.save.setObjectName("save")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.url.setText(_translate("Form", "URL"))
        self.texturl.setPlaceholderText(_translate("Form", "ex : https://en.wikipedia.org/wiki/Machine_learning"))
        self.ringkasan.setText(_translate("Form", "Ringkasan"))
        self.label.setText(_translate("Form", "Dokumen Sumber URL"))
        self.save.setToolTip(_translate("Form", "Simpan"))
        self.save.setText(_translate("Form", "💾"))
